### ISSUE TITLE
备案号有汉字 

### ISSUE THREAD

**Issue by chaojiangcn** [zzzzbw/Fame#1]
有汉字编码不成功，这个怎么解决一下，安装的docker-compose是稳定版的也就是python2.7的

**Comment by zzzzbw** [comment]
你是在.env文件里修改的备案号吗？
文件的编码格式是UTF-8吗

**Comment by zzzzbw** [comment]
文件本身是UTF-8的，但如果你用的编辑器默认不是UTF-8的话，编码格式有可能被改掉
