### ISSUE TITLE
分类页面显示 Bug

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#10]
刚写了一篇博客，只选了分类（生活），没设置标签。发布后发现「分类」页面和数量都无法显示该文章。

应该是查询的时候分类和标签耦合度太高，导致判断失误造成的 Bug。

文章地址 [我又买了一个智能门锁 -- 小米米家智能门锁 VS Aqara（绿米）智能门锁S2](http://www.bihell.com/article/3]

**Comment by zzzzbw** [comment]
已修复，再次保存改文章分类就能正常
