### ISSUE TITLE
新 Markdown 编辑器全屏编辑问题

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#11]
全屏以后，上边和左边并没隐藏，然后再也回不去了。。。
<img width="1680" alt="Screen Shot 2019-05-18 at 23 57 26" src="https://user-images.githubusercontent.com/19926035/57972126-0f160700-79c9-11e9-9f5c-e5dd5d1ef219.png">

**Comment by zzzzbw** [comment]
已修复
