### ISSUE TITLE
文章右侧目录展示问题

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#16]
我发现我其中一篇博客右边的目录跟文章有重叠了。暂时没发现原因，其他的博客都很正常,得找事件看看。。。

地址 http://www.bihell.com/article/6

<img width="1680" alt="Screen Shot 2019-05-24 at 22 08 43" src="https://user-images.githubusercontent.com/19926035/58333681-84be1f00-7e70-11e9-9f3e-7fc8dd00661f.png">

**Comment by zzzzbw** [comment]
我这边显示没问题啊，你分辨率是多少？

**Comment by bihell** [comment]
用的15寸 RMBP    2880 x 1800
我用外接的4K 显示器没问题，但是本子显示就覆盖了。

**Comment by bihell** [comment]
我似乎找到问题了，应该是标题太长，导致右侧目录覆盖到正文上了，看来得设置一个自动换行

**Comment by zzzzbw** [comment]
已修复
