### ISSUE TITLE
fame-admin  网站设置->邮箱设置 开关无效

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#20]
网站设置->邮箱设置 开关无效
只有任意属性修改点击 「保存修改」之后「邮箱设置」开关才会有效。
<img width="1680" alt="Screen Shot 2019-05-26 at 12 11 24" src="https://user-images.githubusercontent.com/19926035/58377302-cb666300-7faf-11e9-9508-c091aeceae70.png">

**Comment by bihell** [comment]
发现设置了「博客网址」之后可以开关可用。  应该有相应判断。

**Comment by zzzzbw** [comment]
在dev分支修复了
