### ISSUE TITLE
发送邮件报错

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#22]
采用新的「网站设置」的邮箱设置，邮件发送错误，空指针提示。

<img width="1920" alt="Screen Shot 2019-05-26 at 12 21 52" src="https://user-images.githubusercontent.com/19926035/58377362-f7ceaf00-7fb0-11e9-94bb-1913bec401b0.png">

**Comment by bihell** [comment]
邮件optionService.get 这边传参有问题
String websiteName = optionService.get(OptionKeys.BLOG_NAME);
String website = optionService.get(OptionKeys.BLOG_WEBSITE);

**Comment by zzzzbw** [comment]
> 邮件optionService.get 这边传参有问题
> String websiteName = optionService.get(OptionKeys.BLOG_NAME);
> String website = optionService.get(OptionKeys.BLOG_WEBSITE);

是的 在dev分支修改了

**Comment by bihell** [comment]
> > 邮件optionService.get 这边传参有问题
> > String websiteName = optionService.get(OptionKeys.BLOG_NAME);
> > String website = optionService.get(OptionKeys.BLOG_WEBSITE);
> 
> 是的 在dev分支修改了

测试了一下可以发送了
