### ISSUE TITLE
dev 版：Fame-admin 后台点「网站设置」报404错误

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#23]
<img width="1920" alt="Screen Shot 2019-05-26 at 16 43 16" src="https://user-images.githubusercontent.com/19926035/58379419-966d0700-7fd5-11e9-813a-b61d42d2ceb5.png">

**Comment by zzzzbw** [comment]
我这边没有出现啊。
现在管理后台已经没有调用`/admin/username`这个接口了，你看看是不是你的版本和我不一样

**Comment by bihell** [comment]
是我版本的问题
