### ISSUE TITLE
更新到最新版本以后 一直有这个报错

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#27]
我直接本地运行 ok，但是正式环境，文章列表页点击「编辑」按钮以后老出现以下错误

![image](https://user-images.githubusercontent.com/19926035/59325237-d857b600-8d14-11e9-9fb1-ee99eddcc3b2.png)

**Comment by zzzzbw** [comment]
我这里没有出现这个问题，你有没有清除页面缓存？

**Comment by bihell** [comment]
应该是缓存的问题，我这两天没碰到这个问题了。
