### ISSUE TITLE
docker axios network error (probably CORS)

### ISSUE THREAD

**Issue by AcodeWang** [zzzzbw/Fame#3]
您好，

看了您关于Docker部署项目的文章非常受益，尝试应用到自己项目的时候出现了 Network error. 可能是关于 axios跨域proxy没有很好的理解。

请问方便通过微信或者Slack和您交流一下么？

**Comment by zzzzbw** [comment]
好吧 我们可以邮件交流。你发我zzzzbw@gmail.com这个邮箱。
