### ISSUE TITLE
快捷键保存文章，重复调用 api

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#30]
这个问题无意中碰到。 新建文章的时候必须有「标题」和「内容」。 昨天我保存的时候。虽然提示我「内容」没有写，但是我发现文章还是创建了。

我猜测应该是网络问题。保存的时候表单验证还没结束。直接「绕过」然后保存了。 暂时无法再现

**Comment by zzzzbw** [comment]
理论上不应当啊，因为校验是在后端做的，不可能由网络原因造成。
你确实成功创建了一个空内容的文章吗

**Comment by bihell** [comment]
是的成功创建。 另外你后端文章内容不是必填的，数据库里面

**Comment by zzzzbw** [comment]
数据库字段不是必填的，但是创建的方法里有校验是否为空

**Comment by bihell** [comment]
嗯，是的，我也奇怪，或者是太晚了，累了= =

**Comment by bihell** [comment]
> 数据库字段不是必填的，但是创建的方法里有校验是否为空

我知道问题在哪里了。我发现我按快捷键保存文章的时候，api有一定概率会调用两次，所以文章「重了」。还没仔细看前端的代码，我记得之前提交快捷键代码之后，你好像有调整过，不知道有没有关系。

**Comment by zzzzbw** [comment]
明白了，那这算表单重复提交的问题。应该后台做出限制，稍后修改
