### ISSUE TITLE
感谢大佬开源

### ISSUE THREAD

**Issue by Jasonandy** [zzzzbw/Fame#31]
搭建成功，感谢大佬开源
![image](https://user-images.githubusercontent.com/12879147/60323789-a94c7000-99b5-11e9-9f1b-883fdb7ebcc8.png)

![image](https://user-images.githubusercontent.com/12879147/60323831-c2552100-99b5-11e9-9737-b906511f1969.png)

**Comment by zzzzbw** [comment]
感谢支持
