### ISSUE TITLE
mapper方法selectMetaDtos 优化建议

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#37]
我在改项目的时候发现 selectMetaDtos 这个方法的性能不太好，每个 id 都要执行一次文章数量 count 的语句。建议修改如下：

    public String selectMetaDtos(String type) {
        StringBuilder sql = new StringBuilder(
                "select t1.id, t1.name, t1.type, count(t3.id) as count\n" +
                "from dice.meta t1\n" +
                "left join dice.middle t2 on t2.m_id = t1.id " +
                "left join dice.article t3 on t3.id = t2.a_id ");
        switch (type) {
            case Types.SNIPPET_TAG:
                sql.append(" and t3.type='" + Types.SNIPPET + "'");
                break;
            case Types.TAG:
                sql.append(" and t3.type='" + Types.POST + "'");
                break;
            default:
        }
        sql.append(" and t3.status != '" + Types.DELETE + "'");
        sql.append(" where 1=1 ");
        sql.append(" and t1.type = #{type} ");
        sql.append(" group by t1.id, t1.name, t1.type");

        log.info("获取属性以及属性下的文章 sql is :" + sql);
        return sql.toString();
    }

**Comment by zzzzbw** [comment]
已经准备改成spring data jpa了，所以这部分逻辑和以前不一样了。
