### ISSUE TITLE
想问下用vue怎么实现右侧的目录树

### ISSUE THREAD

**Issue by ToWeLong** [zzzzbw/Fame#38]
能不能点拨下

**Comment by zzzzbw** [comment]
我是用[tocbot](https://github.com/tscanlin/tocbot/)实现的，你可以去看看

**Comment by ToWeLong** [comment]
> 我是用[tocbot](https://github.com/tscanlin/tocbot/)实现的，你可以去看看

好的  谢谢

**Comment by ToWeLong** [comment]
然后还想问下，就是你网站后台用的编辑器是什么，我看到tocbot只会处理HTML的标题是么？
