### ISSUE TITLE
v2.0.0 docker部署报错，运行时java报错

### ISSUE THREAD

**Issue by greetfish** [zzzzbw/Fame#48]
| ### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'deleted' in 'field list'
fame-server    | ### The error may exist in com/zbw/fame/mapper/SysOptionMapper.java (best guess)
fame-server    | ### The error may involve defaultParameterMap
fame-server    | ### The error occurred while setting parameters
fame-server    | ### SQL: SELECT  id,option_key,option_value,created,modified,deleted  FROM sys_option   WHERE  deleted=0  AND (option_key = ?)
fame-server    | ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'deleted' in 'field list'
fame-server    | ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'deleted' in 'field list'

**Comment by zzzzbw** [comment]
v2.0.0为开发中版本，请使用master的版本

**Comment by greetfish** [comment]
好的，你是不是手动改了数据库表结构

**Comment by zzzzbw** [comment]
是的，改动比较大
