### ISSUE TITLE
Markdown 的链接文字有 Bug

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#7]
http://www.bihell.com/article/1  本文中「安装 Docker」下面的两个「macOS 安装 Docker」只有第一个连接可用，第二个失效。 md 文件这编写试一样的。排查下来试展示的时候 下面一个标题「手动部署（未完成）」把上面的链接挡住了，导致鼠标没法点击。这个不清楚是组件 bug 还是你这边展示 bug

### 安装 Docker

[macOS 安装 Docker](https://docker_practice.gitee.io/install/mac.html)

[macOS 安装 Docker](https://docker_practice.gitee.io/install/mac.html)

**Comment by zzzzbw** [comment]
已修复
