### ISSUE TITLE
手机浏览博客日期不显示

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#8]
文章日期不显示，归档页面日期也不显示
![IMG_1313](https://user-images.githubusercontent.com/19926035/57894927-981f2800-787b-11e9-96a0-2b812ac2b588.PNG)
![IMG_1312](https://user-images.githubusercontent.com/19926035/57894928-98b7be80-787b-11e9-96bb-950357cba805.PNG)

**Comment by zzzzbw** [comment]
已修复
